variables:
    CI_IMAGE_TAG: "opengl"
    MODERNGL_DEBUGGING: "true"
    JULIA_DEPOT_PATH: "$CI_PROJECT_DIR/.julia/"

stages:
    - test
    - documentation
    - refimages

gallerytest:
    stage: test
    image: "juliagpu/julia:v1.2-${CI_IMAGE_TAG}"
    before_script:
        - apt-get -qq update
        # glfw
        - apt-get install -y cmake libxrandr-dev libxinerama-dev libxcursor-dev mesa-utils
        # cairo etc
        - apt-get install -y gettext libpango1.0-0 libcairo2 libmagickwand-6.q16
        - apt-get install -y ffmpeg p7zip-full

    script:
      - mkdir $JULIA_DEPOT_PATH # Pkg.jl#325
      - glxinfo | grep 'version'
      - julia -e 'using InteractiveUtils; versioninfo()'
      - julia --color=yes --project -e "using Pkg; Pkg.pkg\"add AbstractPlotting#master StatsMakie#master Makie#master GLMakie#master GLFW GDAL; resolve; instantiate; test\""

    artifacts:
        when: on_failure
        paths:
        - test/tested_different
        - test/test_recordings
        expire_in: 4 days

deploydocs:
  stage: documentation
  image: "juliagpu/julia:v1.2-${CI_IMAGE_TAG}"
  when: always
  variables:
    DOCUMENTER_DEBUG: "true"
    CI_DEV_PKGS: "Makie AbstractPlotting GLMakie StatsMakie"
  before_script:
      - apt-get -qq update
      # glfw
      - apt-get install -y cmake libxrandr-dev libxinerama-dev libxcursor-dev mesa-utils
      # cairo etc
      - apt-get install -y gettext libpango1.0-0 libcairo2 libmagickwand-6.q16
      - apt-get install -y ffmpeg p7zip-full

  script:
    - julia --project=docs/ -e 'using Pkg;
                                Pkg.add([PackageSpec(path=pwd());
                                         [PackageSpec(name=pkg; rev="master")
                                          for pkg in split(get(ENV,"CI_DEV_PKGS",""))]]);'
    - julia --project=docs/ -e 'using Pkg; Pkg.add(PackageSpec(url = "https://github.com/asinghvi17/Documenter.jl", rev = "as/generic-ci"))'
    - julia --project=docs/ docs/make.jl
  artifacts:
    paths:
    - docs/build
    expire_in: 2 days

deployrefimages:
    stage: refimages
    when: manual
    dependencies:
        - gallerytest
    variables:
        MAKIEGALLERY_REFIMG_PATH: "$CI_PROJECT_DIR/ReferenceImages"
    before_script:
        - git clone https://github.com/SimonDanisch/ReferenceImages
        - pushd ReferenceImages;
                git checkout gitlab-new;
                git push --set-upstream origin;
            popd
    script:
        julia test/upgrade_recordings.jl
